### ISSUE TITLE
Could you give me administrator privileges so that I set up ebook compilation

### ISSUE THREAD

**Issue by jnavila** [progit2-aze/progit2#1]
Hello,

Now that the translation is complete, I would like to set up the compilation chain for generating ebooks and pdf. For this, I need administrator privileges on this repo. 

Thank you.

By the way, there are some errors of compilation right now.

**Comment by alicenab** [comment]
Hello,
Thank you for your request.
Does compilation errors gone now?

**Comment by alicenab** [comment]
I've shared book in large community so there is a possibility that they may fix my translation errors so pdf may be regenerate then.
Can I generate books by myself?

**Comment by jnavila** [comment]
Hello,
You can generate the books by yourself.

I need administrative privileges on this repository in order to set up automatic compilation. 

Please see https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository

This way, each time you push a commit to the repo, the book is built automatically and available on git-scm.com.

**Comment by jnavila** [comment]
Thanks for inviting me. Unfortunately, I still don't have high enough privileges to set up the automatic compilation. I need at least access to Webhooks

**Comment by alicenab** [comment]
I think it should be fixed now

**Comment by jnavila** [comment]
Excuse-me again. It seems I need privileges at the level of the organization.

**Comment by alicenab** [comment]
check please

**Comment by jnavila** [comment]
Can you check the output here: https://github.com/progit2-aze/progit2/releases/tag/2.1.165

**Comment by alicenab** [comment]
Thank you
